from datetime import datetime


SCREEN_WIDTH  = 1920
SCREEN_HEIGHT = 1080

CELL_SIZE = 20
GAME_INTERVAL = 0

START_LIVE_CELL_COUNT = 100

FADE_INTENSITY   = 80
FADE_OUT_TIMEOUT = 10

BUTTON_WIDTH  = 140
BUTTON_HEIGHT = 40

RESTART_BUTTON_X =  SCREEN_WIDTH  * 0.74
RESTART_BUTTON_Y =  SCREEN_HEIGHT * 0.9

END_BUTTON_X =  SCREEN_WIDTH  * 0.9
END_BUTTON_Y =  SCREEN_HEIGHT * 0.9

PAUSE_BUTTON_X =  SCREEN_WIDTH  * 0.82
PAUSE_BUTTON_Y =  SCREEN_HEIGHT * 0.9